// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-p3C-ZYzhpX_8e75eMZHctHzGsRzTSBs',
    appId: '1:829356603722:web:c42690ffef97a3c78269b3',
    messagingSenderId: '829356603722',
    projectId: 'runnn-tbus',
    authDomain: 'runnn-tbus.firebaseapp.com',
    storageBucket: 'runnn-tbus.appspot.com',
    measurementId: 'G-T5ZJ75EVDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnmeJRDbh4eLLmZlLEESSeBsqHwjUbPn0',
    appId: '1:829356603722:android:8e905d9934e22bce8269b3',
    messagingSenderId: '829356603722',
    projectId: 'runnn-tbus',
    storageBucket: 'runnn-tbus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOZvwrvTG0BZHb0jFmGNjbyma6dQwx8pk',
    appId: '1:829356603722:ios:890a2b96930e23808269b3',
    messagingSenderId: '829356603722',
    projectId: 'runnn-tbus',
    storageBucket: 'runnn-tbus.appspot.com',
    iosClientId: '829356603722-kkb0rcvbhq5rdsr4nnka00nm7qqhcrib.apps.googleusercontent.com',
    iosBundleId: 'com.example.runnn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOZvwrvTG0BZHb0jFmGNjbyma6dQwx8pk',
    appId: '1:829356603722:ios:890a2b96930e23808269b3',
    messagingSenderId: '829356603722',
    projectId: 'runnn-tbus',
    storageBucket: 'runnn-tbus.appspot.com',
    iosClientId: '829356603722-kkb0rcvbhq5rdsr4nnka00nm7qqhcrib.apps.googleusercontent.com',
    iosBundleId: 'com.example.runnn',
  );
}
